language: go
go:
  - "1.10.8"

env:
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=darwin  GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=386"

install:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go get github.com/mattn/goveralls github.com/gordonklaus/ineffassign"

script:
  - "go get -ldflags \"-X main.revision=$(git rev-parse HEAD) -X main.version=$(git tag -l 'v*.*.*' --points-at HEAD | sed -n '1s/^v//p')\" -v ./..."
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || GORACE=history_size=7 travis_wait 60 scripts/gotestcover.sh coverage.report"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || ${GOPATH}/bin/ineffassign ."

after_script:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || ${GOPATH}/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source scripts/travis_rename_releases.sh"

deploy:
  api_key:
    secure: pcsVT2uO5n9VnY5NA0GQipzBu7eoye5zuXkdwPD3Ev49Ic7i2+vuYegPawSy7kXM5ppVMU24Ar4q+pMfTgKiLZ2WmIhLXzlUVbx7s2FwnanpbG4ylIq8omGaRETN+1mLI6Kq6uvhaaH5jUG6JuCfpHa2JxlrUilRuAJSzCC7afOuwlKcRLuo0NAzjgLJ/QLT2fH+RJs6YBJuzDZPCw+dqPh/De0vOJ8OE3xukHX8Lax+Hs5lsTTPA5zvb184iIpeG27E0Owd0+zLlY38e8VLILCvEdVPIw4pAN33jmS2tVLUoilq60sYjBo6nA5wSqQk+wP5+vbolOxG8xhCX4drwQLWI07jTxya/r87ljuOXg0nUQMSklLLbJLdAEQg/N2fX42P6VdY92qCvBU4SG/AfvvdimgMmfxN0E5vMpGU949jVlYxR9gO3tW1KHM0YXA/uLl9EqWkThgMqmtyfoY9rfRsnSoQ4lILFMJhZwsJM/JyCGA5oVNVc8I5d/VdAsa44Jg0NlnHP8CMI1bUF3csXKY4X0toJINr4kyLeIUSjHXUaC+uBLP/3mzMquH/NCGjdMUb+86rLOno+lX5t5dEwsWA1FCJ4XvkBV6L+pC1cEzd2GYfohBoDGn5iEwsTVh0h84snsPjyOJOvQS09hVcMn/ZCXKXoV0YoYhIdql3S68=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: winfreddy88/samfile
    tags: true
